// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oykilcmzgrqlelzcrdrs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im95a2lsY216Z3JxbGVsemNyZHJzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3MzE4NTMsImV4cCI6MjA2MjMwNzg1M30.9YOTshLkf3eQ9h8VCHckpsMEsyGTGqPPY6-qYavHBwo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);